### ISSUE TITLE
can not work on hardware I2C?

### ISSUE THREAD

**Issue by manhere** [dirkhillbrecht/UiUiUi#4]
plateform: esp32
screen:  0.96inch, ssd1306_128X64, i2c

work with soft I2C
`U8G2_SSD1306_128X64_NONAME_F_SW_I2C u8g2(U8G2_R0, /* clock=*/ 26, /* data=*/ 27, /* reset=*/ U8X8_PIN_NONE);`

not work with hardware I2C (clock = 22, data = 21):
`U8G2_SSD1306_128X64_NONAME_1_HW_I2C u8g2(U8G2_R0, /* reset=*/ U8X8_PIN_NONE);`

**U8G2_SSD1306_128X64_NONAME_1_HW_I2C** works well in u8g2 example sketchs

**Comment by manhere** [comment]
change to **U8G2_SSD1306_128X64_NONAME_F_HW_I2C**, it works...
`U8G2_SSD1306_128X64_NONAME_F_HW_I2C u8g2(U8G2_R0, /* reset=*/ U8X8_PIN_NONE);`

framebuffer matter? any suggestion?

**Comment by dirkhillbrecht** [comment]
Hi there,

two things:

(1) Uiuiui is built on top of U8g2. The hardware must be supported by U8g2 and if any problems arise with this, check first that U8g2 and its own examples run on the hardware in question.

(2) The non-functioning configuration ends in `..._1_HW_I2C`. As I understand, the "1" indicates that the driver uses a framebuffer of only one row (of 8 pixel rows). This is used for platforms with very limited amount of RAM (e.g. Arduino UNO). In this case, image generation must be performed differently (these infamous "do-while"-loop constructs), and indeed Uiuiui is not tailored for this operation mode. Uiuiui assumes that a _full_ framebuffer exists so that the complete display content can be created and held in memory at once. Those hardware drivers have an "_F_" instead of "_1_" in their name - just as the `..._F_SW_I2C` you mention as functional. I think that the problem is exactly there.

This could be clarified in the Uiuiui documentation.

Best regards,
Dirk

**Comment by manhere** [comment]
It seems that the **framebuffer size** is indeed the reason, thanks for reply
